---

# ====================================================================================================================================

- name: USRSTRAP
  hosts: all

# ------------------------------------------------------------------------------------------------------------------------------------

  vars_files: variables.yml
  gather_facts: true

# ------------------------------------------------------------------------------------------------------------------------------------

  become: true
  become_user: root
  
# ====================================================================================================================================

  roles:
  
# ------------------------------------------------------------------------------------------------------------------------------------

    - {role: system-repos-distro}
    - {role: system-repos-extra}

# ------------------------------------------------------------------------------------------------------------------------------------

    - {role: system-grub}
    - {role: system-update}
    - {role: vbox-additions}
    - {role: packages-development}
    - {role: packages-admintools}

# ------------------------------------------------------------------------------------------------------------------------------------

    - {role: devops-misctools}
    - {role: devops-cloudclis}
    - {role: devops-ansible}

# ------------------------------------------------------------------------------------------------------------------------------------

    - {role: system-clean}
    - {role: system-zero}

# ====================================================================================================================================

  tasks:

# ------------------------------------------------------------------------------------------------------------------------------------


# ====================================================================================================================================

