---

# ====================================================================================================================================

- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mc
    - psmisc
    - tree
    - htop
    - rsync
    - links
    - lynx
    - jq
    - net-tools
    - traceroute
    - telnet
    - whois

# ====================================================================================================================================

- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - dnsutils
  when:
    - (ansible_distribution == "Ubuntu")

# ====================================================================================================================================

