---

# ====================================================================================================================================

- name: DESKTOP
  hosts: all

# ------------------------------------------------------------------------------------------------------------------------------------

  vars_files: variables.yml
  gather_facts: true

# ------------------------------------------------------------------------------------------------------------------------------------

  become: true
  become_user: root
  
# ====================================================================================================================================

  roles:
  
# ------------------------------------------------------------------------------------------------------------------------------------

    - {role: desktop-common}
    - {role: desktop-enhanced}
      
# ====================================================================================================================================

  tasks:

# ------------------------------------------------------------------------------------------------------------------------------------

    - name: Configure Default Runlevel
      file:
        # src: /usr/lib/systemd/system/multi-user.target
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link

    - name: Copy Private Keys
      copy:
        src: "{{ item }}"
        dest: "~/.ssh/"
        mode: 0644
      with_fileglob:
        - "{{ artifacts }}/home/user/.ssh/id_rsa_*.key"

# ====================================================================================================================================

