---

# ====================================================================================================================================

- name: DESKTOP
  hosts: all

# ------------------------------------------------------------------------------------------------------------------------------------

  vars_files: variables.yml
  gather_facts: true

# ------------------------------------------------------------------------------------------------------------------------------------

  become: true
  become_user: root
  
# ====================================================================================================================================

  roles:
  
# ------------------------------------------------------------------------------------------------------------------------------------

    - {role: desktop-common, default_runlevel: "graphical"}
    - {role: desktop-enhanced}
      
# ====================================================================================================================================

  tasks:

# ------------------------------------------------------------------------------------------------------------------------------------

# ====================================================================================================================================

