---

# ====================================================================================================================================

- name: FIREWALL
  hosts: all

# ------------------------------------------------------------------------------------------------------------------------------------

  vars_files: variables.yml
  gather_facts: true

# ------------------------------------------------------------------------------------------------------------------------------------

  become: true
  become_user: root
  
# ====================================================================================================================================

  roles:
  
# ------------------------------------------------------------------------------------------------------------------------------------

    - {role: service-firewall, service_state: true}
    - {role: system-network}
      
# ====================================================================================================================================

  tasks:

# ------------------------------------------------------------------------------------------------------------------------------------


# ====================================================================================================================================

