---

# ====================================================================================================================================

- name: WORK
  hosts: all

# ------------------------------------------------------------------------------------------------------------------------------------

  vars_files: variables.yml
  gather_facts: true

# ------------------------------------------------------------------------------------------------------------------------------------

  become: true
  become_user: "{{ ansible_deployer }}"
  
# ====================================================================================================================================

  roles:
  
# ------------------------------------------------------------------------------------------------------------------------------------

    - {role: work-common}
    - {role: work-repos}

# ====================================================================================================================================

  tasks:

# ------------------------------------------------------------------------------------------------------------------------------------

# ====================================================================================================================================


