---

# ====================================================================================================================================

- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "@Development Tools"
    - autoconf
    - automake
    - gdb
    - python3
    - python3-pip
    - python3-devel
    # - python2
    # - python2-devel
    # - python2-pip
    - json
    # - package
  when:
    - (ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux")

# ------------------------------------------------------------------------------------------------------------------------------------

- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - autoconf
    - automake
    - gdb
    - libffi-dev
    - python3
    - python3-pip
    # - python2
    # - python2-devel
    # - python2-pip
    - libjson-c-dev
    # - package
  when:
    - (ansible_distribution == "Ubuntu")

# ====================================================================================================================================
