---

# ====================================================================================================================================

    - name: Create Directory 
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "~/work"

# ====================================================================================================================================
