---

# ====================================================================================================================================

- name: Configure X-Session
  become: true
  become_user: "{{ ansible_deployer }}"
  copy:
    src: "xinitrc"
    dest: "~/.xinitrc"
    mode: 0644

# ====================================================================================================================================
