---

# ====================================================================================================================================

- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bash-completion
    - zip
    - unzip
    - figlet
    - acl
    - wget
    - vim
    - git
    - python3-pip

# ====================================================================================================================================

