---

# ====================================================================================================================================

- name: LOCALSTRAP
  hosts: all

# ------------------------------------------------------------------------------------------------------------------------------------

  vars_files: variables.yml
  gather_facts: true

# ------------------------------------------------------------------------------------------------------------------------------------

  become: true
  become_user: root
  
# ====================================================================================================================================

  roles:
  
# ------------------------------------------------------------------------------------------------------------------------------------

    - {role: devops-tfenv}
    - {role: devops-packer}

# ------------------------------------------------------------------------------------------------------------------------------------

    - {role: service-docker, service_state: false}
    # - {role: service-docker-web, service_state: false}

# ====================================================================================================================================

  tasks:

# ------------------------------------------------------------------------------------------------------------------------------------


# ====================================================================================================================================

