---

# ====================================================================================================================================

- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ansible

# ====================================================================================================================================
