---

# ====================================================================================================================================

- name: Update Cache
  apt: 
    update_cache: yes
  changed_when: false

- name: Upgrade System
  apt:
    upgrade: yes

# ====================================================================================================================================
