---

# ====================================================================================================================================

- name: Reboot System
  reboot:
    reboot_timeout: 3600
    msg: "Rebooting System..."

# ====================================================================================================================================
