---

# ====================================================================================================================================

- name: Disable SELinux
  selinux:
    state: disabled
  when:
    - (ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux")

- name: Set Timezone
  timezone:
    name: Asia/Yerevan

# ====================================================================================================================================
