---

# ====================================================================================================================================

- name: INFORMATION
  hosts: localhost
  connection: local

# ------------------------------------------------------------------------------------------------------------------------------------

  vars_files: variables.yml
  gather_facts: true

# ------------------------------------------------------------------------------------------------------------------------------------

  become: true
  become_user: root
  
# ====================================================================================================================================

  tasks:

# ====================================================================================================================================

    - name: Host Information
      debug:
        msg: 
          - "User:          {{ ansible_user }}"        
          - "Hostname:      {{ ansible_hostname }}"
          - "Distribution:  {{ ansible_distribution }}"
          - "Major Version: {{ ansible_distribution_major_version }}"
          - "Version:       {{ ansible_distribution_version }}"
          - "Release:       {{ ansible_distribution_release }}"
      when: 
        # - ansible_distribution != "CentOS" and ansible_distribution != "OracleLinux"
        # - ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux"
        # - ansible_distribution == "CentOS"
        # - ansible_distribution == "OracleLinux"
        # - ansible_distribution == "Ubuntu"
        # - ansible_distribution_version < '7'
        # - ansible_distribution_major_version == '6'

# ------------------------------------------------------------------------------------------------------------------------------------

    # - name: Host Facts
    #   debug:
    #     var: ansible_facts

# ------------------------------------------------------------------------------------------------------------------------------------

    # - name: Custom Message
    #   debug:
    #     msg: 
    #       - "{{ lookup('env','ANSIBLE_ROLES_PATH') }}"

# ====================================================================================================================================


