---

# ====================================================================================================================================

- name: USRSTRAP
  hosts: localhost
  connection: local
  
# ------------------------------------------------------------------------------------------------------------------------------------

  vars_files: variables.yml
  gather_facts: true

# ------------------------------------------------------------------------------------------------------------------------------------

  become: true
  become_user: root
  
# ====================================================================================================================================

  roles:
  
# ------------------------------------------------------------------------------------------------------------------------------------

    - {role: system-update}
    - {role: packages-admintools}

# ------------------------------------------------------------------------------------------------------------------------------------

    - {role: devops-misctools}
    - {role: devops-cloudclis}

# ====================================================================================================================================

  tasks:

# ------------------------------------------------------------------------------------------------------------------------------------


# ====================================================================================================================================

