---

# ====================================================================================================================================

- name: Install Services
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - chrony

# ====================================================================================================================================

- name: Configure Services
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - chronyd.service
  when:
    - (ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux")

# ------------------------------------------------------------------------------------------------------------------------------------

- name: Configure Services
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - chrony.service
  when:
    - (ansible_distribution == "Ubuntu")

# ====================================================================================================================================
